### ISSUE TITLE
[1.20.1] Crash when checking items on EMI

### ISSUE THREAD

**Issue by ffuentesm** [Prismwork/EMIffect#7]
EMI 1.0.19+1.20.1+forge - may have caused crash
EMIffect 1.1.0+mc1.20.1 - may have caused crash
![image](https://github.com/Prismwork/EMIffect/assets/44974827/c249ca3f-5705-4bba-8663-0253b5e540aa)
Log: https://crashy.net/ba6b7cc2-68c9-46a0-bb6d-44b279c6f481

**Comment by moechakucha** [comment]
hmm, seems that i wrongly made references of fabric loader in common code? gotta fix it later

**Comment by moechakucha** [comment]
Fixed in https://github.com/Prismwork/EMIffect/commit/eb2f3082c1e67427ef307ab4b27e0da823001cab
