### ISSUE TITLE
[Forge 1.20.1] Crash on startup

### ISSUE THREAD

**Issue by PlayfulPiano** [Prismwork/EMIffect#9]
After adding EMIffect to my modlist (replacing JEED) I've begun to experience this crash on startup. Log comes directly from prism as a proper crash report or latest.log wasn't generated.
https://mclo.gs/xTXH8la

**Comment by unilock** [comment]
Looks like the package for EMIffect's Forge module is wrongly named `emitrades`, making this mod incompatible with EMI Trades.

https://github.com/Prismwork/EMIffect/tree/f27afee3985657cecddd16c42030311aca306b62/forge/src/main/java/io/github/prismwork/emitrades

This should be an easy fix; the package just needs to be renamed.
